jobs:
  run_tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: |
         chmod +x ./OpenCorePackageProdesk/Build-Package
         ./OpenCorePackageProdesk/Build-Package
        shell: bash
